INSERT INTO `ORDER` (ID, USER_ID, TOTAL_PRICE, ADDRESS, EXPRESS_COMPANY, EXPRESS_ID, STATUS, SHOP_ID)
VALUES (2, 1, 700, '火星','顺丰', '运单1234567', 'pending', 1);

INSERT INTO ORDER_GOODS(GOODS_ID, ORDER_ID, NUMBER)
VALUES (1, 2, 3),
       (2, 2, 4);


INSERT INTO `ORDER` (ID, USER_ID, TOTAL_PRICE, ADDRESS, EXPRESS_COMPANY, EXPRESS_ID, STATUS, SHOP_ID)
VALUES (1, 1, 1400, '火星', '顺丰', '运单1234567', 'delivered',1);

INSERT INTO ORDER_GOODS(GOODS_ID, ORDER_ID, NUMBER)
VALUES (1, 1, 5),
       (2, 1, 9);
