package com.wester.order.generate;

import com.wester.api.generate.OrderGoods;
import com.wester.api.generate.OrderGoodsExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface OrderGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_GOODS
     *
     * @mbg.generated Sun Mar 05 23:05:11 CST 2023
     */
    long countByExample(OrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_GOODS
     *
     * @mbg.generated Sun Mar 05 23:05:11 CST 2023
     */
    int deleteByExample(OrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_GOODS
     *
     * @mbg.generated Sun Mar 05 23:05:11 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_GOODS
     *
     * @mbg.generated Sun Mar 05 23:05:11 CST 2023
     */
    int insert(OrderGoods row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_GOODS
     *
     * @mbg.generated Sun Mar 05 23:05:11 CST 2023
     */
    int insertSelective(OrderGoods row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_GOODS
     *
     * @mbg.generated Sun Mar 05 23:05:11 CST 2023
     */
    List<OrderGoods> selectByExample(OrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_GOODS
     *
     * @mbg.generated Sun Mar 05 23:05:11 CST 2023
     */
    OrderGoods selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_GOODS
     *
     * @mbg.generated Sun Mar 05 23:05:11 CST 2023
     */
    int updateByExampleSelective(@Param("row") OrderGoods row, @Param("example") OrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_GOODS
     *
     * @mbg.generated Sun Mar 05 23:05:11 CST 2023
     */
    int updateByExample(@Param("row") OrderGoods row, @Param("example") OrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_GOODS
     *
     * @mbg.generated Sun Mar 05 23:05:11 CST 2023
     */
    int updateByPrimaryKeySelective(OrderGoods row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_GOODS
     *
     * @mbg.generated Sun Mar 05 23:05:11 CST 2023
     */
    int updateByPrimaryKey(OrderGoods row);
}